### ISSUE TITLE
Very good

### ISSUE THREAD

**Issue by dannynotsmart** [VarMonke/is-cute#1]
Very good

**Comment by justanotherbyte** [comment]
agreed

**Comment by VarMonke** [comment]
This was a very tactical decision after I decided to explain myself and tell people who I truly am. I truly am cute.

**Comment by Makonede** [comment]
when imposter sus

**Comment by VarMonke** [comment]
Your mom.

**Comment by CnyAnime** [comment]
> Very good

agreed

**Comment by LeoCx1000** [comment]
Ass.
